/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaces;

import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import mundo.ConectarDB;

/**
 *
 * @author cmch05
 */
public class MenuPrincipal extends javax.swing.JFrame {

    boolean suiche=false;
    public MenuPrincipal() {
        initComponents();
        
        cargarCombo();
        antesCerrar();
    }
    // previene la aslida y despues escucha el boton de salida y le dice que haga algo
    public void antesCerrar(){
        setDefaultCloseOperation(MenuPrincipal.DO_NOTHING_ON_CLOSE);
        addWindowListener(new WindowAdapter() {
            public void windowClosing(WindowEvent e){
                registarSalida();
            }
            
        });
        
        
                // setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
    }
    
    public void registarSalida(){
        ConectarDB conectar =new ConectarDB();
                Connection con= conectar.coneccion();
                int ser=0;
                 String sSQL2 ="select serial from bitacora "
                    + "order by serial desc limit 1 ";
                try {
                    PreparedStatement pst = con.prepareStatement(sSQL2);
                    ResultSet rs= pst.executeQuery(sSQL2);
                    while(rs.next()){
                    ser=rs.getInt("serial");
                    
                    }
                     JOptionPane.showMessageDialog(null, ser);
                    sSQL2="update bitacora set fecha_salida = curdate() , hora_salida = curtime() "
                    + "where serial ='"+ser+"' ";
                    //pst= con.prepareStatement(sSQL2);
                    pst.executeUpdate(sSQL2);
                    
                } catch (SQLException ex) {
                    JOptionPane.showMessageDialog(null, "error "+ex);
                    //Logger.getLogger(MenuPrincipal.class.getName()).log(Level.SEVERE, null, ex);
                }
                //this.dispose();
                if(suiche==true){
                    this.dispose();
                    Login login =new Login();
                    login.setVisible(suiche);
                }
                else{
                    
                System.exit(0);
                }
    }
    public void cargarCombo(){
        ConectarDB coneccion =new ConectarDB();
        String contador="";
        String sSQL="",sSQL2="";
        sSQL="select count(*) from usuario";
        sSQL2= "show tables";
        Connection con = coneccion.coneccion();
        try {
            PreparedStatement pst= con.prepareStatement(sSQL2);
            ResultSet rs=pst.executeQuery(sSQL2);
            while(rs.next()){
                cboTablas.addItem(rs.getString(1));
            }
          //  JOptionPane.showMessageDialog(null, "exito ");
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "error "+ex);
            //Logger.getLogger(MenuPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    public void contarRegistros(){
        ConectarDB coneccion =new ConectarDB();
        String contador="";
        String  sSQL2="",
                total=(cboTablas.getSelectedItem().toString()),
                a ="";
        sSQL2="select count(*) from "+total;
        //sSQL2= "show tables";
        Connection con = coneccion.coneccion();
        try {
            PreparedStatement pst= con.prepareStatement(sSQL2);
            ResultSet rs=pst.executeQuery(sSQL2);
            while(rs.next()){
                a=rs.getString(1);
            }
            
            JOptionPane.showMessageDialog(null, "Total registros de "+total+ " son "+a);
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "error "+ex);
            //Logger.getLogger(MenuPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnSalida = new javax.swing.JButton();
        cboTablas = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnSalida.setText("CerrarSesión");
        btnSalida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalidaActionPerformed(evt);
            }
        });

        cboTablas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cboTablasMouseClicked(evt);
            }
        });
        cboTablas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboTablasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(284, Short.MAX_VALUE)
                .addComponent(btnSalida)
                .addGap(21, 21, 21))
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(cboTablas, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(104, 104, 104)
                .addComponent(cboTablas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 142, Short.MAX_VALUE)
                .addComponent(btnSalida)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalidaActionPerformed
        // TODO add your handling code here:
        suiche=true;
        registarSalida();
        
        
    }//GEN-LAST:event_btnSalidaActionPerformed

    private void cboTablasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboTablasActionPerformed
        // TODO add your handling code here:
        contarRegistros();
    }//GEN-LAST:event_cboTablasActionPerformed

    private void cboTablasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cboTablasMouseClicked
        // TODO add your handling code here:
        
    }//GEN-LAST:event_cboTablasMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSalida;
    private javax.swing.JComboBox<String> cboTablas;
    // End of variables declaration//GEN-END:variables
}
